FROM python:3.12-slim
EXPOSE 80
WORKDIR /app
COPY pyproject.toml /app/pyproject.toml
COPY main.py /app/main.py
COPY src /app/src

RUN pip install uv
RUN uv venv --python 3.12 && uv sync --no-cache

CMD ["/bin/bash", "-c", "source .venv/bin/activate && python main.py"]
