input:
    service:
          CSVService:         
              path: my_input_file.csv        # some input csv
          XLSXService:         
              path: my_input_file2.xlsx      # some input xls

output:
    service:
          PickleService:
              path: sub_clm_out.pkl       
  
